syntax enable
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set number
set relativenumber
set showmatch
set incsearch
set hlsearch
set ignorecase
set smartcase
set hidden
set timeout timeoutlen=3000 ttimeoutlen=100 " So Shift-O is fast
set viminfo='20,<1000,s1000

:command W w
nnoremap ; :
